ALTER TABLE "matching_questions"
ADD COLUMN IF NOT EXISTS "config_json" jsonb DEFAULT '{}'::jsonb NOT NULL;
--> statement-breakpoint
DROP INDEX IF EXISTS "matching_profiles_user_id_unique";
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "matching_profiles_user_program_unique" ON "matching_profiles" USING btree ("user_id","program");
--> statement-breakpoint
UPDATE "matching_questions"
SET
  "active" = false,
  "updated_at" = now()
WHERE "program" = 'vibe';
--> statement-breakpoint
INSERT INTO "matching_questions" (
  "id",
  "program",
  "version",
  "section",
  "order",
  "prompt",
  "help_text",
  "required",
  "input_type",
  "max_length",
  "config_json",
  "websearch",
  "active"
)
VALUES
  (
    'vibe_linkedin_url',
    'vibe',
    '2026-03-15',
    'passive',
    1,
    'LinkedIn URL (optional)',
    'Drop your LinkedIn if it is the fastest way for us to understand what you do.',
    false,
    'url',
    null,
    '{"placeholder":"https://linkedin.com/in/..."}'::jsonb,
    true,
    true
  ),
  (
    'vibe_links_about_you',
    'vibe',
    '2026-03-15',
    'passive',
    2,
    'Links about you (optional)',
    'Website, portfolio, projects, social profiles, talks, writing, or anything else that helps capture you.',
    false,
    'multi_url',
    null,
    '{"placeholder":"https://..."}'::jsonb,
    true,
    true
  ),
  (
    'vibe_links_about_topics',
    'vibe',
    '2026-03-15',
    'passive',
    3,
    'Links & media you love (optional)',
    'Articles, podcasts, books, shows, people, or rabbit holes that help us understand your taste.',
    false,
    'multi_text',
    300,
    '{"placeholder":"e.g. Ezra Klein podcast, The Leftovers, David Whyte, urbanism newsletters"}'::jsonb,
    true,
    true
  ),
  (
    'vibe_resume',
    'vibe',
    '2026-03-15',
    'passive',
    4,
    'Resume / background dump (optional)',
    'Upload a PDF resume or paste portfolio, bio, or background text if you want the matching to have more context.',
    false,
    'file_markdown',
    20000,
    '{"placeholder":"Paste background, bio, portfolio notes, or resume text here"}'::jsonb,
    false,
    true
  ),
  (
    'vibe_scary_movies',
    'vibe',
    '2026-03-15',
    'survey',
    1,
    'Do you like scary movies?',
    'A classic low-effort signal.',
    false,
    'single_select',
    null,
    '{"phase":"phase1","options":[{"value":"yes","label":"Yes"},{"value":"no","label":"No"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_sailboat',
    'vibe',
    '2026-03-15',
    'survey',
    2,
    'Wouldn''t it be fun to chuck it all and go live on a sailboat?',
    'Adventure versus stability, without sounding like a personality test.',
    false,
    'single_select',
    null,
    '{"phase":"phase1","options":[{"value":"absolutely","label":"Absolutely"},{"value":"no_thanks","label":"No thanks"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_traveled_alone',
    'vibe',
    '2026-03-15',
    'survey',
    3,
    'Have you ever traveled alone to another country?',
    null,
    false,
    'single_select',
    null,
    '{"phase":"phase1","options":[{"value":"yes","label":"Yes"},{"value":"not_yet","label":"Not yet"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_weekend_mode',
    'vibe',
    '2026-03-15',
    'survey',
    4,
    'On weekends, are you more likely to try something completely new or perfect something you already love?',
    null,
    false,
    'single_select',
    null,
    '{"phase":"phase1","options":[{"value":"new","label":"Try something new"},{"value":"perfect","label":"Perfect something I already love"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_social_energy',
    'vibe',
    '2026-03-15',
    'survey',
    5,
    'What kind of social energy usually feels best to you?',
    null,
    false,
    'single_select',
    null,
    '{"phase":"phase1","options":[{"value":"one_on_one","label":"Intimate 1:1 conversations"},{"value":"group","label":"Big group energy"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_idea_style',
    'vibe',
    '2026-03-15',
    'survey',
    6,
    'When exploring ideas, what style feels more natural?',
    null,
    false,
    'single_select',
    null,
    '{"phase":"phase1","options":[{"value":"debate","label":"Debate and challenge assumptions"},{"value":"build","label":"Build on ideas together"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_abstract_concrete',
    'vibe',
    '2026-03-15',
    'survey',
    7,
    'What kind of conversation do you usually gravitate toward?',
    null,
    false,
    'single_select',
    null,
    '{"phase":"phase1","options":[{"value":"abstract","label":"Big abstract ideas and possibilities"},{"value":"concrete","label":"Concrete projects and real problems"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_depth_breadth',
    'vibe',
    '2026-03-15',
    'survey',
    8,
    'In conversations, what tends to feel better?',
    null,
    false,
    'single_select',
    null,
    '{"phase":"phase1","options":[{"value":"deep","label":"Go deep on one topic"},{"value":"broad","label":"Bounce across many topics"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_circadian',
    'vibe',
    '2026-03-15',
    'survey',
    9,
    'Night owl or early bird?',
    null,
    false,
    'single_select',
    null,
    '{"phase":"phase1","options":[{"value":"night_owl","label":"Night owl"},{"value":"early_bird","label":"Early bird"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_grammar',
    'vibe',
    '2026-03-15',
    'survey',
    10,
    'Does spelling and grammar matter to you?',
    null,
    false,
    'single_select',
    null,
    '{"phase":"phase1","options":[{"value":"yes","label":"Yes, it matters"},{"value":"not_really","label":"Not really"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_descriptors',
    'vibe',
    '2026-03-15',
    'survey',
    11,
    'Pick up to 5 words that describe you',
    'Choose the ones that feel closest.',
    false,
    'multi_select',
    null,
    '{"phase":"phase1","maxSelections":5,"options":[{"value":"curious","label":"Curious"},{"value":"ambitious","label":"Ambitious"},{"value":"playful","label":"Playful"},{"value":"analytical","label":"Analytical"},{"value":"empathetic","label":"Empathetic"},{"value":"rebellious","label":"Rebellious"},{"value":"practical","label":"Practical"},{"value":"creative","label":"Creative"},{"value":"philosophical","label":"Philosophical"},{"value":"spontaneous","label":"Spontaneous"},{"value":"intense","label":"Intense"},{"value":"chill","label":"Chill"},{"value":"nerdy","label":"Nerdy"},{"value":"adventurous","label":"Adventurous"},{"value":"warm","label":"Warm"},{"value":"independent","label":"Independent"},{"value":"weird","label":"Weird"},{"value":"driven","label":"Driven"},{"value":"sensitive","label":"Sensitive"},{"value":"bold","label":"Bold"},{"value":"grounded","label":"Grounded"},{"value":"optimistic","label":"Optimistic"},{"value":"skeptical","label":"Skeptical"},{"value":"funny","label":"Funny"},{"value":"organized","label":"Organized"},{"value":"romantic","label":"Romantic"},{"value":"calm","label":"Calm"},{"value":"chaotic","label":"Chaotic"},{"value":"loyal","label":"Loyal"},{"value":"visionary","label":"Visionary"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_topics',
    'vibe',
    '2026-03-15',
    'survey',
    12,
    'Pick up to 5 topics you could talk about for hours',
    'Shared interests are strong conversation fuel.',
    false,
    'multi_select',
    null,
    '{"phase":"phase1","maxSelections":5,"options":[{"value":"ai","label":"AI / technology"},{"value":"philosophy","label":"Philosophy"},{"value":"startups","label":"Startups"},{"value":"psychology","label":"Psychology"},{"value":"art_design","label":"Art / design"},{"value":"travel","label":"Travel"},{"value":"health_fitness","label":"Health / fitness"},{"value":"music","label":"Music"},{"value":"food","label":"Food / cooking"},{"value":"science","label":"Science"},{"value":"history","label":"History"},{"value":"spirituality","label":"Spirituality"},{"value":"politics","label":"Politics"},{"value":"climate","label":"Climate"},{"value":"parenting","label":"Parenting"},{"value":"sports","label":"Sports"},{"value":"film_tv","label":"Film / TV"},{"value":"fashion","label":"Fashion"},{"value":"finance","label":"Finance"},{"value":"relationships","label":"Relationships"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_help_with',
    'vibe',
    '2026-03-15',
    'survey',
    13,
    'Pick up to 3 things you love helping people with',
    null,
    false,
    'multi_select',
    null,
    '{"phase":"phase1","maxSelections":3,"options":[{"value":"career","label":"Career advice"},{"value":"creative","label":"Creative projects"},{"value":"emotional","label":"Emotional support"},{"value":"fitness","label":"Fitness / health"},{"value":"cooking","label":"Cooking"},{"value":"tech","label":"Tech problems"},{"value":"decisions","label":"Thinking through big decisions"},{"value":"introductions","label":"Introductions / networking"},{"value":"learning","label":"Learning new skills"},{"value":"home","label":"Home projects"},{"value":"writing","label":"Writing"},{"value":"feedback","label":"Honest feedback"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_values',
    'vibe',
    '2026-03-15',
    'survey',
    14,
    'Rank your top 3 from these 6 in order of what matters most to you right now',
    'Pick and order your top 3.',
    false,
    'ranking',
    null,
    '{"phase":"phase1","maxSelections":3,"options":[{"value":"growth","label":"Learning and growth"},{"value":"meaning","label":"Building something meaningful"},{"value":"relationships","label":"Deep relationships"},{"value":"adventure","label":"Adventure and new experiences"},{"value":"impact","label":"Making an impact"},{"value":"freedom","label":"Freedom and flexibility"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_conversation_vibes',
    'vibe',
    '2026-03-15',
    'survey',
    15,
    'Rank these conversation vibes in order of preference',
    'Pick and order your top 3.',
    false,
    'ranking',
    null,
    '{"phase":"phase1","maxSelections":3,"options":[{"value":"laughing","label":"Laughing until it hurts"},{"value":"mind_blown","label":"Mind-blown by a new idea"},{"value":"understood","label":"Feeling truly understood"},{"value":"solving","label":"Solving a problem together"},{"value":"vulnerable","label":"Swapping vulnerable stories"}]}'::jsonb,
    false,
    true
  ),
  (
    'vibe_stranger_depth',
    'vibe',
    '2026-03-15',
    'survey',
    16,
    'How deep do you like to go with strangers?',
    null,
    false,
    'slider',
    null,
    '{"phase":"phase1","sliderMin":1,"sliderMax":10,"sliderStep":1,"minLabel":"Light and playful","maxLabel":"Deep and real"}'::jsonb,
    false,
    true
  ),
  (
    'vibe_zero_prep_talk',
    'vibe',
    '2026-03-15',
    'survey',
    17,
    'What could you give a 20-minute talk on with zero preparation?',
    null,
    false,
    'short_text',
    240,
    '{"phase":"phase2","placeholder":"A niche interest, obsession, or domain you know cold"}'::jsonb,
    false,
    true
  ),
  (
    'vibe_motto',
    'vibe',
    '2026-03-15',
    'survey',
    18,
    'What''s your motto or life bumper sticker?',
    null,
    false,
    'short_text',
    180,
    '{"phase":"phase2","placeholder":"A phrase or one-liner that captures your vibe"}'::jsonb,
    false,
    true
  ),
  (
    'vibe_overhyped',
    'vibe',
    '2026-03-15',
    'survey',
    19,
    'What''s a trend you think is totally overhyped?',
    null,
    false,
    'short_text',
    180,
    '{"phase":"phase2","placeholder":"A trend, idea, or cultural thing you are skeptical of"}'::jsonb,
    false,
    true
  ),
  (
    'vibe_current_challenge',
    'vibe',
    '2026-03-15',
    'survey',
    20,
    'What''s a challenge you''re working through right now?',
    null,
    false,
    'short_text',
    240,
    '{"phase":"phase2","placeholder":"A problem, transition, or tension that is real for you right now"}'::jsonb,
    false,
    true
  ),
  (
    'vibe_learning_30_days',
    'vibe',
    '2026-03-15',
    'survey',
    21,
    'If you could spend 30 days learning anything, what would it be?',
    null,
    false,
    'short_text',
    180,
    '{"phase":"phase2","placeholder":"A skill, topic, craft, or field you would dive into"}'::jsonb,
    false,
    true
  ),
  (
    'vibe_love_being_asked',
    'vibe',
    '2026-03-15',
    'survey',
    22,
    'What''s a question you love being asked?',
    null,
    false,
    'short_text',
    180,
    '{"phase":"phase2","placeholder":"A question that brings out something good in you"}'::jsonb,
    false,
    true
  ),
  (
    'vibe_rabbit_hole',
    'vibe',
    '2026-03-15',
    'survey',
    23,
    'What''s a book, podcast, show, or rabbit hole that''s shaped how you think?',
    null,
    false,
    'short_text',
    240,
    '{"phase":"phase2","placeholder":"Name it and say why it stuck with you"}'::jsonb,
    false,
    true
  ),
  (
    'vibe_surprise',
    'vibe',
    '2026-03-15',
    'survey',
    24,
    'What''s something about you that would surprise most people?',
    null,
    false,
    'short_text',
    220,
    '{"phase":"phase2","placeholder":"A hidden layer, weird fact, or unexpected part of your story"}'::jsonb,
    false,
    true
  )
ON CONFLICT ("id") DO UPDATE
SET
  "program" = EXCLUDED."program",
  "version" = EXCLUDED."version",
  "section" = EXCLUDED."section",
  "order" = EXCLUDED."order",
  "prompt" = EXCLUDED."prompt",
  "help_text" = EXCLUDED."help_text",
  "required" = EXCLUDED."required",
  "input_type" = EXCLUDED."input_type",
  "max_length" = EXCLUDED."max_length",
  "config_json" = EXCLUDED."config_json",
  "websearch" = EXCLUDED."websearch",
  "active" = EXCLUDED."active",
  "updated_at" = now();
