// Known Asheville venues - these map directly to "Asheville"
// These are venues that don't include city info in their location string
export const ASHEVILLE_VENUES = [
  // Major music venues
  "the orange peel",
  "the grey eagle",
  "pulp", // Part of Orange Peel complex
  "harrah's cherokee center",

  // Breweries & bars
  "cultivated cocktails",
  "sovereign kava",
  "sweeten creek brewing",
  "ginger's revenge",
  "one world brewing",
  "westville pub",
  "the funkatorium",
  "wicked weed",
  "burial beer",
  "highland brewing",
  "green man brewery",
  "catawba brewing",
  "bhramari brewing",
  "wedge brewing",
  "archetype brewing",
  "zillicoah beer",
  "french broad brewery",

  // Other venues
  "the odd",
  "the hop ice cream",
  "biltmore village",
  "haywood park hotel",
  "montford area",
  "uphora dance",
  "grove arcade",
  "pack square",
  "pritchard park",
  "biltmore house",
  "biltmore estate",
  "us cellular center",
  "thomas wolfe auditorium",
  "diana wortham",
  "asheville community theatre",
  "magnetic theatre",

  // Parks & outdoor
  "carrier park",
  "french broad river park",
  "richmond hill park",
  "beaver lake",
];

// Known NC cities in the Asheville area (ordered by likely frequency)
export const KNOWN_CITIES = [
  "Asheville",
  "Black Mountain",
  "Weaverville",
  "Hendersonville",
  "Arden",
  "Candler",
  "Swannanoa",
  "Fletcher",
  "Mills River",
  "Brevard",
  "Waynesville",
  "Mars Hill",
  "Woodfin",
  "Leicester",
  "Fairview",
  "Burnsville",
  "Morganton",
  "Flat Rock",
  "Clyde",
  "Barnardsville",
  "Enka",
  "Boone",
  "Blowing Rock",
  "Banner Elk",
  "Maggie Valley",
  "Marshall",
  // Additional NC cities from analysis
  "Lake Lure",
  "Sylva",
  "Canton",
  "Bryson City",
  "Lake Junaluska",
  "Cedar Mountain",
  "Rutherfordton",
  "Lake Toxaway",
  "Franklin",
  "Newland",
  "Royal Pines",
  "Pisgah Forest",
  "Highlands",
  "Cashiers",
  "Spruce Pine",
  "Marion",
  "Old Fort",
  "Tryon",
  "Saluda",
  "Columbus", // NC Columbus (there's also SC, but we'll assume NC in context)
  "Mill Spring",
  "Chimney Rock",
  "Bat Cave",
  "Montreat",
  "Ridgecrest",
];
